services:
  - type: web
    name: pinokiox-frontend
    runtime: static
    buildCommand: pnpm install && pnpm build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://backend-1-hbvq.onrender.com"
      - key: VITE_USE_MOCK
        value: "false"
      - key: VITE_MOCK_DELAY
        value: "true"
      - key: VITE_SHOW_DEBUG
        value: "false"
